name: Generate Pacman Graph

on:
  # Se ejecuta cada 24 horas
  schedule:
    - cron: "0 0 * * *"
  # Permite ejecutarlo manualmente
  workflow_dispatch:
  # Se ejecuta cuando haces push a la rama principal
  push:
    branches:
    - master
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-pacman
    permissions:
      contents: write
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Pacman Graph
        # Usamos la acción oficial de abozanona
        uses: abozanona/pacman-contribution-graph@v2
        with:
          github_user_name: ${{ github.repository_owner }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to Output Branch
        # Esta acción sube los archivos generados a la rama "output"
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
